### ISSUE TITLE
Button inside slide not working on iOS

### ISSUE THREAD

**Issue by tsaboin** [TheOriginalJosh/nativescript-intro-slides#1]
Hi,
Please take a look at this:

        <IntroSlides:IntroSlides>
    		<IntroSlides:Slide class="intro-slide-1">
    			<Label text="This is Panel 1"  />
    		</IntroSlides:Slide>
    		<IntroSlides:Slide class="intro-slide-2">
    			<Label text="This is Panel 2"  />
    		</IntroSlides:Slide>
    		<IntroSlides:Slide class="intro-slide-3">
    			<Label text="This is Panel 3"  />
    		</IntroSlides:Slide>
    		<IntroSlides:Slide class="intro-slide-4">
    			<Label text="This is Panel 4"  />
    		</IntroSlides:Slide>
    		<IntroSlides:Slide class="intro-slide-5">
                <StackLayout>
                	<Label text="This is Panel 5"  />
                    <Button text="Get Started" tap="getStarted" />
                </StackLayout>
    		</IntroSlides:Slide>
	</IntroSlides:IntroSlides>

The tap event on the button in slide 5 does not occur on iOS but works fine on Android.

What could be the cause?

Cheers.

**Comment by TheOriginalJosh** [comment]
Thank you for the feedback, I'm working on a fix for this and will let you know as soon as I have it figured out. 

I have figured out that it's a conflict with the "touch" event on the slide and the button "tap" event. So I'm halfway there :D 

I appreciate you letting me know about this.

**Comment by TheOriginalJosh** [comment]
And I found the fix! Thank you for pointing this out again. I have a major update coming and the fix will be included in it.

**Comment by tsaboin** [comment]
@TheOriginalJosh great. Will watchout for the update. Cheers.

**Comment by TheOriginalJosh** [comment]
I've published a beta version with fix and several enhancements to npm if you want to try it out. you will have to specify the below version in your package.json file.

nativescript-intro-slides@0.1.1

**Comment by tsaboin** [comment]
hi @TheOriginalJosh I will give it a try shortly. Appbuilder currently not building for iOS. I think Telerik builder is having issues. But will try from command line and give you my comments.

**Comment by tsaboin** [comment]
@TheOriginalJosh It worked very fine on both iOS and Android. Good job boss.

**Comment by TheOriginalJosh** [comment]
@tsaboin Sweet! I'm planning on releasing this and some more in an update shortly. Let me know if you have any more problems. Thanks for your help again!

**Comment by tsaboin** [comment]
@TheOriginalJosh I noticed new updates, what's new in them?

**Comment by TheOriginalJosh** [comment]
@tsaboin, overall improvements really and the animations are all in sync.along with screen rotation support.

**Comment by tobydeh** [comment]
Hi @TheOriginalJosh, I'm facing the same problem in another project - Button tap events don't seem to work when inside a container with a Touch event listener. What was your solution?

**Comment by TheOriginalJosh** [comment]
@tobydeh could you tell me which slides npm package you have installed?
